create table urls (
    id bigint generated by default as identity primary key,
    short_code varchar(16) unique,
    original_url varchar(2048) not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone,
    click_count bigint not null default 0,
    last_accessed_at timestamp with time zone,
    active boolean not null default true,
    version bigint not null default 0
);

create index idx_urls_short_code on urls (short_code);
